2024-12-15 18:58:08  兴效能初始化成功，点击“开始”启动自动化
2024-12-15 18:58:16  自动化终止 (JSONDecodeError)，1分钟后尝试重启自动化

2024-12-15 18:58:24  自动化终止 (JSONDecodeError)，1分钟后尝试重启自动化

2024-12-15 18:58:28  出现异常：Expecting value: line 1 column 1 (char 0) (JSONDecodeError)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "d:\python\兴效能正式版\autogui.py", line 3841, in get_data
    self.DATA.update(self.update_data())
                     ^^^^^^^^^^^^^^^^^^
  File "d:\python\兴效能正式版\autogui.py", line 3723, in update_data
    self.get_session()
  File "d:\python\兴效能正式版\autogui.py", line 3693, in get_session
    ).json()
      ^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2024-12-15 18:58:46  自动化终止 (JSONDecodeError)，1分钟后尝试重启自动化

2024-12-15 18:58:53  出现异常：Expecting value: line 1 column 1 (char 0) (JSONDecodeError)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "d:\python\兴效能正式版\autogui.py", line 3841, in get_data
    self.DATA.update(self.update_data())
                     ^^^^^^^^^^^^^^^^^^
  File "d:\python\兴效能正式版\autogui.py", line 3723, in update_data
    self.get_session()
  File "d:\python\兴效能正式版\autogui.py", line 3693, in get_session
    ).json()
      ^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
2024-12-15 18:59:17  自动化终止 (JSONDecodeError)，1分钟后尝试重启自动化

2024-12-15 18:59:20  自动化终止 (JSONDecodeError)，1分钟后尝试重启自动化

2024-12-15 18:59:22  自动化终止 (JSONDecodeError)，1分钟后尝试重启自动化

2024-12-15 19:00:18  兴效能初始化成功，点击“开始”启动自动化
2024-12-15 19:00:23  自动化终止 (JSONDecodeError)，1分钟后尝试重启自动化

2024-12-15 19:00:39  出现异常：Expecting value: line 1 column 1 (char 0) (JSONDecodeError)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "d:\python\兴效能正式版\autogui.py", line 3829, in get_data
    self.DATA.update(self.update_data())
                     ^^^^^^^^^^^^^^^^^^
  File "d:\python\兴效能正式版\autogui.py", line 3711, in update_data
    self.get_session()
  File "d:\python\兴效能正式版\autogui.py", line 3681, in get_session
    ).json()
      ^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
